### PR TITLE
Fix processing of metric attributes on variants

### PR DESCRIPTION
**Pull request by palviggi-flagbit**
Trying to implement configurable products using the new option for using metric attributes as variants I found a couple of problems in the implementation.

1) It fails if the attributes have uppercase letters (in our case we had some camelCased names). There are 2 points of failure:
    1) When saving the config in the admin, it uses the original name, but in the import attribute job it lowercases the name before comparing with the config to see it it should be a "_select" type.
    2) When creating the options during the product import, it compares the value from the config against the column names, but the column names are lowercased during insertDataFromApi() so it fails to create any option.
2) When creating the Options, Job\Product and Job\Option use different ways to get a default locale and creation might fail because of a validation on Job\Option::insertOptions().
Both methods query the same config path, but use different scope, and in the case of our multilocale store it returned different values.
Job\Product uses `\Magento\Backend\Model\Locale\Manager::getGeneralLocale()` (scope default)
Job\Option uses `\Akeneo\Connector\Helper\Config::getDefaultLocale()` (scope store)

For 1), I applied lowercasing on the appropiate part of the process (it could be done at the config save in the backend, but didn't want to affect something else). For 2), I used the the locales setup on Akeneo, so the value is in all of them.
Also I removed a duplicated call to array_key_exists

### CODE REVIEW

**Comment by Dnd-Gimix** [comment]
Hello @palviggi-flagbit  ,

Thank you for your contribution on Akeneo connector for Magento 2 !

We have added some changes to it.
Your changes will be added in a future release.

Many thanks.

Regards,

**Comment by arduibag** [comment]
Hi @palviggi-flagbit , 

I'm Marketplace Manager at Akeneo.
We are very interested in your contribution and would like to integrate it into our **Enterprise** version of **Akeneo Connector for Magento 2**.
If you agree with this, would it be possible for you to fill in this online form and reply to this message to let us know if you have done so?:
https://www.akeneo.com/contributor-license-agreement/

Thank you very much,

Michaël

**Comment by palviggi-flagbit** [comment]
> Hi @palviggi-flagbit ,
> 
> I'm Marketplace Manager at Akeneo.
> We are very interested in your contribution and would like to integrate it into our **Enterprise** version of **Akeneo Connector for Magento 2**.
> If you agree with this, would it be possible for you to fill in this online form and reply to this message to let us know if you have done so?:
> https://www.akeneo.com/contributor-license-agreement/
> 
> Thank you very much,
> 
> Michaël

I filled the form.

**Comment by arduibag** [comment]
Thanks a lot @palviggi-flagbit for your quick answer and your agreement!

**Comment by Dnd-Gimix** [comment]
Hello @palviggi-flagbit ,

Your contribution has been integrated in the release 100.3.3 of the connector.
Thanks again for your contribution.

Regards,

**Pull request merged**
