### PR TITLE
Fixes "Row size too large" error

### PR DESCRIPTION
**Pull request by bakkerpj**
This fixes the "Row size too large" error which may occur when synchronizing the product_model.

Akeneo Connector has a hardcoded setting that updates product_model per 500 products, which can result in a very large database UPDATE statement. In our case well over 500 Kbyte while our (managed) hosting provider only allows for 8 Kbyte updates.

This PR will parameterize the hardcoded 500 setting -- aka "Batch Size". When set to 0, it will then slice the individual UPDATE statement into even smaller UPDATEs as determined by "Update Size". It may be slower, but the database won't abort with "Row size too large" error. These settings can be found in `Stores -> Configuration -> Catalog -> Akeneo Connector -> Advanced`.

Similar issues mentioned here:
https://github.com/Agence-DnD/PIMGento-2-API/issues/153
https://github.com/Agence-DnD/PIMGento-2/issues/97

--Peter

### CODE REVIEW

**Comment by Dnd-Gimix** [comment]
Hello @bakkerpj ,

Thank you for your contribution !
We will analyze your changes and come back to you.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @bakkerpj   ,

Thanks again for your contribution on Akeneo connector for Magento 2 !

We have added some changes to it and we wil be adding your changes in a future release.

Many thanks.

Regards,

**Comment by arduibag** [comment]
Hi @bakkerpj , 

I'm Marketplace Manager at Akeneo.
We are very interested in your contribution and would like to integrate it into our **Enterprise** version of **Akeneo Connector for Magento 2**.
If you agree with this, would it be possible for you to fill in this online form and reply to this message to let us know if you have done so?:
https://www.akeneo.com/contributor-license-agreement/

Thank you very much,

Michaël

**Comment by Dnd-Gimix** [comment]
Hello @bakkerpj  ,

Your contribution has been integrated in the community release version 100.3.3 of the connector.
Thanks again for your contribution.

Regards,

**Pull request merged**
